### ISSUE TITLE
Connecting to wrong Ledger address (incorrect HD Derivation Path)

### ISSUE THREAD

**Issue by Hex-Capital** [AugurProject/augur-app#103]
Version: Windows Desktop Client v1.0.0

When I connect my ledger, the default address shown is incorrect. According to MEW, the address showing up in the Augur app is using the wrong HD derivation path:

HD Derivation Path
 m/44'/60'/0'/0
Jaxx, Metamask, Exodus, imToken, TREZOR (ETH) & Digital Bitbox

Instead of the HD Derivation Path Ledger is supposed to use:

m/44'/60'/0'
Ledger (ETH)

**Comment by TacoByte** [comment]
This was discussed in the discord. Apparently, it's the others that are using the wrong derivation path. Choosing your own derivation is a potential future feature according to a dev

**Comment by Hex-Capital** [comment]
Hmm if all other sources are defaulting to m/44'/60'/0', maybe Augur should as well for now?

Moving my funds from m/44'/60'/0' to m/44'/60'/0'/0 would make them inaccessible on all other 3rd party ledger integrations

**Comment by joeykrug** [comment]
> Moving my funds from m/44'/60'/0' to m/44'/60'/0'/0 would make them inaccessible on all other 3rd party ledger integrations

You can actually access them in myetherwallet, mycrypto etc by clicking on the thing at the top left when using ledger.
Selecting it yourself in augur will be a new ui feature
