### ISSUE TITLE
Unable to connect to local Parity node - invalid token

### ISSUE THREAD

**Issue by Hex-Capital** [AugurProject/augur-app#105]
Version: Windows Desktop Client v1.0.0

When trying to connect to my local Parity node, I'm getting the following error:

Blocked connection from https://localhost:8080 using invalid token

Note that Augur is able to sync just fine. I think this error only pops up when trying to load the UI in Chrome

What Parity settings are needed for Augur to be able to connect via websockets?

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/13772/github-unable-to-connect-to-local-parity-node-invalid-token

**Comment by adrake33** [comment]
Closing this for now. @Hex-Capital Please let me know if this should be re-opened.
