### ISSUE TITLE
Disconnects when clicking submit when Purchasing " Participation Tokens " 

### ISSUE THREAD

**Issue by fadisaaida** [AugurProject/augur-app#113]
[log.txt](https://github.com/AugurProject/augur-app/files/2182791/log.txt)
i use windows 10 64bit, chrome latest version, all my other ethereum nodes ( parity,geth ) closed, using the augur app with infura mainnet. 

once i open the app and connect to my ledger, i go to dispute tab and try to purchase some tokens, after the review page i click submit and then app disconnect from the ethereum node, the app itself
 does not crash.

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/13773/github-disconnects-when-clicking-submit-when-purchasing-participation-tokens

**Comment by Metang386** [comment]
same issue using infura.

**Comment by joeykrug** [comment]
This seems to be an issue a lot of people are having

**Comment by fafrd** [comment]
I have a similar (but not quite same) problem. Mine seems to stay connected to the eth node, but just spits "Error: unknown account" to the console: 
![image](https://user-images.githubusercontent.com/5905628/42741738-e1eeb48a-8882-11e8-9547-819194ec5a1e.png)

hoping this gets fixed before the window closes in 2 days 😬😬😬

**Comment by fafrd** [comment]
still having this problem in 1.0.4

**Comment by nuevoalex** [comment]
Discovered the cause of the problem. Should be fixed in an upcoming release when this gets merged and released: https://github.com/AugurProject/augur-ui/pull/2020

**Comment by sharkcrayon** [comment]
This should be fixed now. Closing.
