### ISSUE TITLE
"Nuke database" doesn't work

### ISSUE THREAD

**Issue by TacoByte** [AugurProject/augur-app#115]
High Sierra

The "Reset to delete database and configuration file" button doesn't do what it advertises. I have checked the Application Support/augur folder and everything is still there. When I click the button, it says "Resetting" for a second, then reverts back and nothing else happens. Event doesn't generate a log that I can find

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/13774/github-nuke-database-doesn-t-work

**Comment by sharkcrayon** [comment]
@TacoByte Can you retest and let us know if this is working for you with the 1.0.4 release? The Reset Database option is now in the app's Settings menu.
