### ISSUE TITLE
When providing initial liquidity while creating a market, I can't cancel an order

### ISSUE THREAD

**Issue by TacoByte** [AugurProject/augur-app#117]
On the "Liquidity" screen of the market creation process

If you add an order, you should be able to cancel it as well. If you make a mistake or change your mind, you have to start over the whole market creation process instead of just being able to cancel your order. In fact, you have to refresh the page to clear the cache

I can currently go back and edit any detail about my market, except for this.

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/13775/github-when-providing-initial-liquidity-while-creating-a-market-i-can-t-cancel-an-order

**Comment by justinbarry** [comment]
This was handled here: https://github.com/AugurProject/augur-ui/pull/2055 and released here: https://github.com/AugurProject/augur-app/releases/tag/v1.0.6
