### ISSUE TITLE
geth --syncmode light doesn't work as a source for augur-node

### ISSUE THREAD

**Issue by TacoByte** [AugurProject/augur-app#122]
`geth --syncmode light --rpc`

I am running the latest geth on augur 1.0.2.

Augur node seems confused by the remaining block count and doesn't let me open the client page. Note the info in the upper right 

![screen shot 2018-07-11 at 14 42 58](https://user-images.githubusercontent.com/8594622/42572006-f4953112-8518-11e8-98f9-19301a06bee8.png)

**Comment by toffoo** [comment]
It is working for me.  Your screenshot looks right, I don't see the problem.

**Comment by bthaile** [comment]
In the next augur-app we add a wait indicator, which means augur-node is downloading log and getting ready to process. 
The animated ... will replace the Blocks Remaining dash.

**Comment by bthaile** [comment]
There is a log file that will give you more information. Check the augur-app repo README for location.

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/13778/github-geth-syncmode-light-doesn-t-work-as-a-source-for-augur-node

**Comment by bthaile** [comment]
Fixed in version 1.0.3, we added a wait indicator. The blockchain logs are being downloaded.

**Comment by sharkcrayon** [comment]
@TacoByte Can you test this again with the latest app release?

**Comment by toffoo** [comment]
Syncing 1.0.4 with geth --syncmode light is still working good for me
