### ISSUE TITLE
Allow customization of localhost port

### ISSUE THREAD

**Issue by vanjan** [AugurProject/augur-app#127]
Hi there, 

I've got something running on 8080 already -- can I tell Augur App to use a different port?

**Comment by bthaile** [comment]
I totally agree, we will discuss this feature and prioritize and I hope to have it impl soon.

**Comment by patrickmcgillivray** [comment]
Related to port 8080 -- a local instance of Parity (with default settings) blocks requests to this port as unauthorized and requests a token (Parity signer token?). I see recommended settings for using Geth locally in the Augur documentation. However, I have not been able to find instructions regarding settings or command line flags for Parity.

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/13782/github-allow-customization-of-localhost-port

**Comment by sharkcrayon** [comment]
@vanjan This is implemented in v1.0.5. Please see directions here: https://github.com/AugurProject/augur-app#running-ui-on-different-port-change-from-8080
