### ISSUE TITLE
Feature Request: Initial Liquidity both Buy and Sell

### ISSUE THREAD

**Issue by page1** [AugurProject/augur-app#129]
Currently when creating a market you can only place a liquidity order on the buy or sell side, but not both. To promote liquidity users should have the option to place liquidity orders on both sides of the order book on market creation.

**Comment by joeykrug** [comment]
You can do both [if it's not letting you, this is a bug so reopen]

**Comment by page1** [comment]
Once I click "Add order" for the buy order it grays out the options and won't let me submit a sell order

<img width="955" alt="screen shot 2018-07-12 at 12 43 40 pm" src="https://user-images.githubusercontent.com/6609556/42652974-3e19dbcc-85d1-11e8-9396-f36502206b13.png">

**Comment by page1** [comment]
@joeykrug I don't think I have the ability to reopen.

**Comment by sharkcrayon** [comment]
https://app.clubhouse.io/augur/story/14835/github-only-able-to-add-buy-initial-liquidity

**Comment by bthaile** [comment]
@page1 I'm not seeing this behavior. I can create both buy and sell orders for initial liquidity.

Are you still having this issue. 

Are you saying that the SELL form is disabled? you can't add shares or price?

**Comment by bthaile** [comment]
Reopen this issue if you see it again, closing
