### ISSUE TITLE
Feature Request: Open Orders

### ISSUE THREAD

**Issue by page1** [AugurProject/augur-app#130]
I haven't found a way to see what orders I currently have open.

**Comment by page1** [comment]
Some way to understand how much "Buying Power" I have left would be great. And understand how much "risk" I have outstanding waiting for markets to resolve.

**Comment by joeykrug** [comment]
It shows in the markets page and portfolio page

**Comment by page1** [comment]
I think the reason I'm not seeing any orders is because of #134
