### ISSUE TITLE
Checksums and developer signatures not available on release page

### ISSUE THREAD

**Issue by jacoblyles** [AugurProject/augur-app#132]
I'd like to be able to verify the checksums and signatures of the binaries I download and run on my machine. Adding that extra step ensures that the binary I'm running is the same one that left the developer's machine or build bot. I like that. 

Lacking that adds GitHub as a trusted third party. That's fine for now. But it would be nice to eliminate that assumption. 

The release page is here: https://github.com/AugurProject/augur-app/releases

**Comment by bthaile** [comment]
Yes, we’ll publish the checksum. Thanks for the heads up.

**Comment by petong** [comment]
We are working on getting individual checksums for the installers, currently as a stopgap we are publishing latest.yml and latest-mac.yml, which have the checksums for the windows installers and the mac installers.

**Comment by petong** [comment]
checksum files planned for 1.0.5 release.

**Comment by justinbarry** [comment]
CH ticket https://app.clubhouse.io/augur/story/13701/publish-installer-checksums-for-users-to-verify

**Comment by justinbarry** [comment]
Checkums now provided. See release page here: https://github.com/AugurProject/augur-app/releases
