### ISSUE TITLE
Major: Some issue with publicTrade method?

### ISSUE THREAD

**Issue by negamax** [AugurProject/augur-app#134]
There are several transactions where ETH is simply getting returned back to the account

https://etherscan.io/token/0xd5524179cb7ae012f5b642c1d6d700bbaa76b96b?a=0x24e2b1d415e6e0d04042eaa45dc2a08fc33ca6cd

**Comment by bthaile** [comment]
This is an known issue, we have a fix to come out in next release. Currently testing. Look for the next version of augur-app, releasing soon.

**Comment by negamax** [comment]
@bthaile can I ask what's causing this issue and what fix is being applied to remedy it?

**Comment by nuevoalex** [comment]
@negamax The relevant fix can be found here: https://github.com/AugurProject/augur.js/commit/17388be965f57c5d2d292e414e91c6bb557db8a3

The trading functions this used to call have on contract gas minimums on them which are far higher than the gas actually required to do the trades. We patched trading to get estimates that are accurate which made them lower than the on contract minimums.

This change switches to using trading functions without these on contract minimum gas requirements.
