### ISSUE TITLE
Feature Request : Disable bets on markets after closing time

### ISSUE THREAD

**Issue by negamax** [AugurProject/augur-app#139]
Augur UI currently allows bet taking on markets even when they are further to the time set by the creator. Bet taking on these markets should be disabled with possibly a notification or some other cue

**Comment by bthaile** [comment]
We keep the markets open for trading forever. Thats the way the smart contracts are written. 

This allows for winners to sell shares and free up their ETH for other trading. 

It also opens up traders who dont mind waiting to trade and make a little profit just for being patient.

**Comment by negamax** [comment]
@bthaile thanks. Both scenarios are interesting and should be supported.
