### ISSUE TITLE
Unable to choose an address when connecting via Ledger

### ISSUE THREAD

**Issue by SantasNotReal** [AugurProject/augur-app#149]
After opening the app, with ssl enabled for Ledger, and connecting via Ledger, there's no way to choose an address to connect with. 

A suggestion: I'm not sure how MyEtherWallet sorts their address list when connecting via Ledger, but it would be nice to default in the same manner.

**Comment by page1** [comment]
Hi @SantasNotReal 
Checkout these other issues that are probably related to your experience. #103 #75 

#103 is probably the most important to you

**Comment by SantasNotReal** [comment]
@page1 Thank you for pointing those out!
