### ISSUE TITLE
When i refresh the ui screen it logs me out (using trezor)

### ISSUE THREAD

**Issue by Chehands** [AugurProject/augur-app#157]

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/14116/github-when-i-refresh-the-ui-screen-it-logs-me-out-using-trezor

**Comment by sharkcrayon** [comment]
@Chehands This is expected behavior at the moment, though we are discussing changing this. I'll post an update here when I have one.

**Comment by CptanPanic** [comment]
Yes I am struggling with this issue also.  I would like to use the improved search/sort at predictions.global but am not able to actually bring up markets that I find because it then logs me out of wallet.

**Comment by bthaile** [comment]
We'll be working on an auto-login and manual logout feature.

**Comment by adrake33** [comment]
Issue moved to [AugurProject/augur #336](https://github.com/AugurProject/augur/issues/336) via [**ZenHub**](https://www.zenhub.com/)
