### ISSUE TITLE
Can the width of the category and tag bars be made manually adjustable?

### ISSUE THREAD

**Issue by Chehands** [AugurProject/augur-app#159]
The categories and tags are difficult to read and differentiate between.

**Comment by sharkcrayon** [comment]
@Chehands You mean on the Markets page right? The sidebars that list categories and tags?

I think we need to overhaul that section in a larger way. Making the width of those columns adjustable seems like a really stop-gap measure to a large UI problem.

**Comment by sharkcrayon** [comment]
https://app.clubhouse.io/augur/story/13900/discuss-markets-list-cat-tag-menu-changes
