### ISSUE TITLE
Failed download - Network error

### ISSUE THREAD

**Issue by Janjanjanjajaja** [AugurProject/augur-app#160]
dear devs, i keep trying to download the augur - 1.0.3 dmg file and at the end its stops ands states: Failed - Network error

Can anyone clarify what this is?

Thanks

**Comment by justinbarry** [comment]
Are you trying to download from here? https://github.com/AugurProject/augur-app/releases/tag/v1.0.3

**Comment by Janjanjanjajaja** [comment]
Hey Justin, now it worked fine. Thanks

Op vr 13 jul. 2018 om 20:37 schreef Justin <notifications@github.com>:

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/14122/github-failed-download-network-error
