### ISSUE TITLE
WIN 10 PRO - DESK TOP APP CLOSES.NO ERROR MESSAGE.BROWSER DISCONNECTS. 

### ISSUE THREAD

**Issue by greenriverneo** [AugurProject/augur-app#164]
[log.log](https://github.com/AugurProject/augur-app/files/2194495/log.log)

**Comment by petong** [comment]
@greenriverneo Can you install the 1.0.4 release and see if you still have issues?

https://github.com/AugurProject/augur-app/releases/tag/v1.0.4

**Comment by greenriverneo** [comment]
Trying now....

*Thomas J. Suich*
*IL Licensed Attorney, Managing Broker, CPA*
*317 Grape Vine Trail, Oswego, IL 60543*
*c: (630) 815.7073*
*f: (888) 885.0725*
*tsuichlaw@gmail.com <tsuichlaw@gmail.com> *

*BE AWARE!  ONLINE BANKING FRAUD IS ON THE RISE.  IF YOU RECEIVE AN EMAIL
FROM MY OFFICE CONTAINING WIRE TRANSFER INSTRUCTIONS, PLEASE CALL MY OFFICE
IMMEDIATELY.  *


*I DO NOT EVER SEND WIRE INSTRUCTIONS!*

**Comment by greenriverneo** [comment]
I did a clean install and it works great.  I am trying to make my first bet
but mask pops up twice and i confirm both times, the app tells me order
placed by I do not see it anywhere nor on etherscan.  Maybe network lag.
Nice job on the fix, very stable!



*Thomas J. Suich*
*IL Licensed Attorney, Managing Broker, CPA*
*317 Grape Vine Trail, Oswego, IL 60543*
*c: (630) 815.7073*
*f: (888) 885.0725*
*tsuichlaw@gmail.com <tsuichlaw@gmail.com> *

*BE AWARE!  ONLINE BANKING FRAUD IS ON THE RISE.  IF YOU RECEIVE AN EMAIL
FROM MY OFFICE CONTAINING WIRE TRANSFER INSTRUCTIONS, PLEASE CALL MY OFFICE
IMMEDIATELY.  *


*I DO NOT EVER SEND WIRE INSTRUCTIONS!*

**Comment by greenriverneo** [comment]
I see them pending in the app.  I made two.  Looking good!

*Thomas J. Suich*
*IL Licensed Attorney, Managing Broker, CPA*
*317 Grape Vine Trail, Oswego, IL 60543*
*c: (630) 815.7073*
*f: (888) 885.0725*
*tsuichlaw@gmail.com <tsuichlaw@gmail.com> *

*BE AWARE!  ONLINE BANKING FRAUD IS ON THE RISE.  IF YOU RECEIVE AN EMAIL
FROM MY OFFICE CONTAINING WIRE TRANSFER INSTRUCTIONS, PLEASE CALL MY OFFICE
IMMEDIATELY.  *


*I DO NOT EVER SEND WIRE INSTRUCTIONS!*

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/14193/github-win-10-pro-desk-top-app-closes-no-error-message-browser-disconnects
