### ISSUE TITLE
No Transcation History /Not All Markets Showing

### ISSUE THREAD

**Issue by Anastik** [AugurProject/augur-app#165]
I have the Augur App currently installed on my desktop and laptop. I have about 10 REP on my account. On my desktop the Augur App isn't showing all the active markets or my transaction history of buying participation tokens. Whereas on my laptop more markets are showing up and my transaction history is available. 

I'm running Augur App 1.0.3 on both the desktop and laptop; I've tried uninstalling and reinstalling the Augur App on my desktop and this hasn't fixed the issue.

**Comment by nuevoalex** [comment]
@Anastik Could you provide your log file here?

You can find it depending on OS at:

```
MacOS : ~/Library/Application\ Support/augur

Windows : %AppData%\augur

Linux : ~/.augur
```

Thanks!

**Comment by Anastik** [comment]
@nuevoalex I'm in this folder but which file do you need in particular?

**Comment by nuevoalex** [comment]
@Anastik the file named `log`

**Comment by Anastik** [comment]
<img width="773" alt="screen shot 2018-07-13 at 9 56 58 pm" src="https://user-images.githubusercontent.com/33998307/42721460-d4140dac-86e7-11e8-8a90-9cb964fd0687.png">

Here's the only thing I see under that file path. And I'm also showing hidden files if that's an issue. Am I looking in the wrong spot? @nuevoalex

**Comment by bthaile** [comment]
Log locations


on Linux: ~/.config/Augur/log.log
on OS X: ~/Library/Logs/augur/log.log
on Windows: %USERPROFILE%\AppData\Roaming\augur\log.log

**Comment by Anastik** [comment]
Thanks @bthaile! Here you go:

[log.log](https://github.com/AugurProject/augur-app/files/2194718/log.log)

Of note you can also see the difference between my REP that's listed and the actual REP in my wallet. Again all of the balances and markets are updating correctly on my laptop. 

![screen shot 2018-07-13 at 10 33 46 pm](https://user-images.githubusercontent.com/33998307/42721777-0334c734-86ed-11e8-9fec-a187bceeb962.png)

**Comment by bthaile** [comment]
Have you grabbed the newest version of augur-app? Are you still having issues? We have had some issues with data gaps. They should be fixed in the newest release 1.0.4

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/14195/github-no-transaction-history-markets-not-showing-at-all

**Comment by Anastik** [comment]
Yep this is fixed now. Closing out the issue.
