### ISSUE TITLE
UI: If I cancel the transaction for fillOrder from market screen, the bids in orderbook become un-selectable 

### ISSUE THREAD

**Issue by negamax** [AugurProject/augur-app#168]
1. Open any market
2. Select an order and buy/sell -> review -> confirm
3. **Cancel** the transaction

Now as a user I can't interact with the orderbook at all.

**Comment by bthaile** [comment]
https://app.clubhouse.io/augur/story/14181

**Comment by bthaile** [comment]
Can you still reproduce this issue?

**Comment by negamax** [comment]
I can't make 1.05 sync. Waiting for 1.06. If it works, I will give this a try and write back.

**Comment by sharkcrayon** [comment]
@negamax 1.0.6 is available now. People have been running into issues syncing with Infura, so if you're using them you might try some different endpoints. These are an option:

http://gethstar.com/ethereum-http
ws://gethstar.com/ethereum-ws

**Comment by negamax** [comment]
@bthaile this is no longer happening on 1.06. Fixes many issues. Onwards and forwards!

@sharkcrayon thanks, 1.06 rules!
