### ISSUE TITLE
There is no AppImage release file

### ISSUE THREAD

**Issue by stobiewan** [AugurProject/augur-app#174]
The releases contain files for Windows, Mac and Debian. Why not replace the Debian file with an AppImage so all Linux distros have an option? With Solus currently have to build from source. It's made worse that the build scripts also rely on apt.

**Comment by petong** [comment]
we plan on releasing a snap package in addition to .deb files, can look into appimage as well.

**Comment by sharkcrayon** [comment]
Adding this to our internal issue tracker: https://app.clubhouse.io/augur/story/14836/github-add-appimage-release-file

**Comment by bthaile** [comment]
been addressed.
