### ISSUE TITLE
Search : A bug, maybe hiding a bigger issue

### ISSUE THREAD

**Issue by negamax** [AugurProject/augur-app#175]
Can't find 0xa0af46c9ece9228aa47ee778f7f97d9222b551f5 market "Will the total amount of USD staked on Augur (mainnet) exceed 1 million USD 1 week after launch? (10:00AM UTC on July 17th)" when I search for Augur

**Comment by bthaile** [comment]
The search box is a keyword search and is limited to only searching markets the UI has loaded. 

Currently search is limited and is a issue we plan on fixing in a future release.

**Comment by bthaile** [comment]
Also you can click on any market and notice the id in the url. Replace the id with your id. You can get to that market that way.

**Comment by negamax** [comment]
@bthaile Thanks. Just to highlight, this was at the max zoom level when no category was selected.

**Comment by negamax** [comment]
@bthaile id replacement doesn't work. Tried with and without description key

**Comment by bthaile** [comment]
Just curious, what url did you try after replacing the id?

**Comment by gwern** [comment]
Replacing the ID does work for me, but first causes an error (the "Error: Sorry, something went wrong! Try reloading this page or returning home." message), requiring a force-reload, and then it apparently starts a new Augur app session requiring me to sign back into Metamask. Which is a very frustrating way to work around the search being useless. (To find any new market, I have to use `predictions.global` to sort by an interesting trait like size or closing-soon, find the market ID, paste it in, fail, force-refresh, go to the account tab to log back in, go back to the Markets tab to find it again, and only then do I actually have access to it.)

**Comment by bthaile** [comment]
Yes, this is annoying, it’s on our radar. 

https://app.clubhouse.io/augur/story/14650/fix-direct-marketid-urls

**Comment by bthaile** [comment]
Yes, this is annoying, it’s on our radar. 

https://app.clubhouse.io/augur/story/14650/fix-direct-marketid-urls

**Comment by bthaile** [comment]
@negamax are you still seeing this issue? in the next release will have the ability to search on market id.
