### ISSUE TITLE
Feature Request: Manually choose Data Folder

### ISSUE THREAD

**Issue by GroovyGrovesy** [AugurProject/augur-app#182]
As the title says, I'd like to be able to choose the data folder as I have a small ssd C: drive.

I've tried using '-datadir=E:\Crypto\Augur' like in other wallets but with no success.

Thanks

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/14203/github-feature-request-manually-choose-data-folder

**Comment by GroovyGrovesy** [comment]
What's that??? I'm not signing up so you'll have to tell me!

**Comment by petervecchiarelli** [comment]
@GroovyGrovesy haha it's just a way for us to track what issues have been submitted and who's working on these in our internal project management tool.

**Comment by adrake33** [comment]
Issue moved to [AugurProject/augur #343](https://github.com/AugurProject/augur/issues/343) via [**ZenHub**](https://www.zenhub.com/)
