### ISSUE TITLE
Standby/Sleep Support

### ISSUE THREAD

**Issue by page1** [AugurProject/augur-app#183]
I feel like when my computer comes out of standby Augur tends to show that it's 100% synced, but if I restart Augur it will sync a very large number of blocks suggesting that it wasn't actually synced automagically after the computer woke from sleep.

It would be great if the sync would resume after wake from sleep.

**Comment by page1** [comment]
Confirming picture of not resuming after sleeping computer overnight.
<img width="826" alt="screen shot 2018-07-18 at 7 36 46 am" src="https://user-images.githubusercontent.com/6609556/42885175-87b1ecee-8a5d-11e8-940b-af6944ac0e24.png">

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/14204/github-standby-sleep-support

**Comment by sharkcrayon** [comment]
Support for auto-reconnecting is available in the latest release 👍. Closing.
