### ISSUE TITLE
Ability to change default 8080 web port from electron app

### ISSUE THREAD

**Issue by hoffmabc** [AugurProject/augur-app#191]
As a web developer I often have an app server running on 8080. It would be convenient to be able to change that port from the UI or at least have the ability to do so when there's a conflict.

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/14207/github-ability-to-change-default-8080-web-port-from-electron-app

**Comment by Bomper** [comment]
This is a dupe of #127, please close.

**Comment by hoffmabc** [comment]
As long as it’s acknowledged that this should be possible through the electron UI in fine with that.

**Comment by tomkysar** [comment]
@hoffmabc definitely have gotten this feedback before & agree, it's on the road-map for some point in the near future.

**Comment by hoffmabc** [comment]
Awesome. Looking forward to it.

**Comment by sharkcrayon** [comment]
@hoffmabc This is implemented in v1.0.5. Please see directions here: https://github.com/AugurProject/augur-app#running-ui-on-different-port-change-from-8080

**Comment by hoffmabc** [comment]
Thanks @sharkcrayon
