### ISSUE TITLE
Timezone Support

### ISSUE THREAD

**Issue by page1** [AugurProject/augur-app#195]
I sort of wish I could pick the timezone the app works in. Since its a global market I'd love to just leave it in UTC instead of my local time.

**Comment by page1** [comment]
I've made a few markets with some departures between the markets expiration and the descriptive text because of not getting the timezone's right. Specifically when creating markets that pass Day Light Savings boundary's.

Keeping it all in UTC everywhere would help avoid this

**Comment by page1** [comment]
Maybe some markdown or something would make it easy to put the market expiration time in the title and description so they always say the same thing.

**Comment by joeykrug** [comment]
UI should show when a market was created imo + allow user to pick a timezone imo

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/14281/github-timezone-support

**Comment by adrake33** [comment]
Issue moved to [AugurProject/augur #342](https://github.com/AugurProject/augur/issues/342) via [**ZenHub**](https://www.zenhub.com/)
