### ISSUE TITLE
Phantom orders on *some* order books

### ISSUE THREAD

**Issue by negamax** [AugurProject/augur-app#196]
I have seen this on multiple markets. Could be related to gas issue where certain amount is required to activate further trigger

E.g. 0x212cd5cf0fe10d858b458f31291f4a4a43cf623c and 0xb6010f3fd93434cbdd98d68b71984030a0156a56 

have some orders on sell *green* side which can't be taken. Seems like multiple people have tried as there's one buy bid higher than the sell

**Comment by nuevoalex** [comment]
@negamax This is a known issue related to orderbooks we're working out a solution to currently. We should have a fix and more information in an upcoming release

**Comment by negamax** [comment]
@nuevoalex good to know this is known
