### ISSUE TITLE
Not Able to Create A Market With Trezor on Augur

### ISSUE THREAD

**Issue by Sm00g15** [AugurProject/augur-app#197]
Everything is correct, and when I go to click "Submit" I get hit with this error: 

![screen shot 2018-07-19 at 11 26 19 am](https://user-images.githubusercontent.com/14209806/42913036-bdb74070-8b46-11e8-8ecc-ac76bb730220.jpg)

**Comment by nuevoalex** [comment]
@Sm00g15 There should be a red notice in your browser bar which you can click to enable popups then try again

**Comment by Sm00g15** [comment]
Yup that worked! Thank you!

For any that run into this issue make sure you click “Always show popups from localhost:8080” but ALSO CLICK THE LINK to get the popup to display immediately.

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/14282/github-not-able-to-create-a-market-with-trezor-on-augur
