### ISSUE TITLE
Can not sync blocks

### ISSUE THREAD

**Issue by gggh000** [AugurProject/augur-app#204]
It become unresponsive at block 0 sync. Using Windows 10 : 
Using win-augur-1.0.x.exe after installation.

**Comment by Anastik** [comment]
@gggh000 Are you updating from a previous version of the Augur App? As in did you have v 1.0.3 installed and you're now updating to v 1.0.4?

**Comment by gggh000** [comment]
IT says below the version is 1.0.4. Thanks.,

**Comment by BrianSipple** [comment]
Not to spam -- just helping to keep track -- but this seems to be related to #202, #194, #190, and #188.

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/14286/github-cannot-sync-blocks

**Comment by harriswarren** [comment]
Mainnet on Infura seems to not sync.   Anyone have a good alternate Mainnet Augur endpoint?  I am trying to avoid a local version.  For Augur to be successful this has to be easier...  I am still trying to access the outcome of the World Cup.

Is this just an Ethereum sync issue?

**Comment by junw3i** [comment]
same issue as @harriswarren

**Comment by CptanPanic** [comment]
Yes same issue here with new install

**Comment by bthaile** [comment]
Usimg the community provided ethereum endpoints should help with syncing. Closing

**Comment by gggh000** [comment]
used on AWS WinServer 2012, it stuck on 23.66% with 1.0.5.

**Comment by gggh000** [comment]
I am outta here and come back in a year, by that time, hopefully it is smooth sailing.

**Comment by gggh000** [comment]
1.0.6 version much better but not there yet: 
@ 82.36%, got server error.
