### ISSUE TITLE
Feature Request & Idea: Make markets with liquidity easier to find

### ISSUE THREAD

**Issue by page1** [AugurProject/augur-app#205]
When browsing in the markets tab its currently difficult to find markets that have interesting bids/asks/depth/rate of change.
<img width="982" alt="screen shot 2018-07-19 at 12 15 26 pm" src="https://user-images.githubusercontent.com/6609556/42961923-84dde27a-8b4d-11e8-8d49-4df962e6bf2d.png">
There are a lot of ways to address this (Filters, sorting) but I think a cool visual (if sticking with the current layout) would be the addition of some red and green best bid and ask tick marks next to the last price/mid noted in the picture as 50%. This would signal if there was liquidity, what side it's on, at what price, and maybe even the shade or thickness of the ticks could denote how much is available.

Just an idea. Since it's not an issue, should I close this immediately?

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/14287/github-feature-request-idea-make-markets-with-liquidity-easier-to-find

**Comment by sharkcrayon** [comment]
@page1 This is on our roadmap :) We should be getting to it in the near future.

**Comment by joeykrug** [comment]
Someone made an example image of this that was a bit different but that looked gorgeous in the trading channel in discord

**Comment by adrake33** [comment]
Closing this since https://app.clubhouse.io/augur/story/12974/add-green-and-red-up-and-down-arrows-to-last-price is marked as Completed. Please let me know if there is any reason why this issue should remain open.
