### ISSUE TITLE
Add icon for the Linux app

### ISSUE THREAD

**Issue by Bomper** [AugurProject/augur-app#209]
I've just installed the .deb and noticed it lacks an application icon.

**Comment by tomkysar** [comment]
cc: @petong

**Comment by sharkcrayon** [comment]
https://app.clubhouse.io/augur/story/14290/github-add-icon-for-the-linux-app

**Comment by Bomper** [comment]
@sharkcrayon: are there publicly available credentials for Clubhouse? It asks me to login.

**Comment by sharkcrayon** [comment]
@Bomper Sorry, just posted that up there as a way to track that it's been added to our internal issue tracking system.

We'll be taking care of that soon.

**Comment by bthaile** [comment]
been addressed.
