### ISSUE TITLE
Wrong SHA-256 Hash For win-Augur-1.0.5.exe

### ISSUE THREAD

**Issue by michaelcippolito** [AugurProject/augur-app#223]
I am calculating
`b8dadd6d015b4586ce3a6561c66eed44f583c6d66061ed42f65851371a15cf45`
for the hash of the file located at https://github.com/AugurProject/augur-app/releases/download/v1.0.5/win-Augur-1.0.5.exe

This does not match
`cc5fe7da635366b9e6ac29e38d9b53016cf9913f68d9077f13df7babd8382093`
as listed at https://github.com/AugurProject/augur-app/releases/download/v1.0.5/win-Augur-1.0.5.exe.sha256

I have downloaded https://github.com/AugurProject/augur-app/releases/download/v1.0.5/win-Augur-1.0.5.exe multiple times and used multiple programs to check the hash, all with the same results.

**Comment by michaelcippolito** [comment]
Specific clarification:
b8dadd6d015b4586ce3a6561c66eed44f583c6d66061ed42f65851371a15cf45
is the _SHA-256_ hash of https://github.com/AugurProject/augur-app/releases/download/v1.0.5/win-Augur-1.0.5.exe

**Comment by mbalance** [comment]
I'm pretty sure they're not supposed to match like that.

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/14477/github-wrong-sha-256-hash-for-win-augur-1-0-5-exe
