### ISSUE TITLE
Feature: Auto connect

### ISSUE THREAD

**Issue by page1** [AugurProject/augur-app#227]
I'm betting most users are not going to change these settings. And even those that do will probably always want to connect to the same endpoints. Adding a little "remember my selection", or "connect automatically next time?" check box would reduce the complexity of this app.

<img width="557" alt="screen shot 2018-07-23 at 12 00 34 pm" src="https://user-images.githubusercontent.com/6609556/43094439-1af0b114-8e70-11e8-9b45-764159630115.png">

Obviously with this change some way to go back and make changes in the future would be needed.(Possibly part of the "settings" dropdown

**Comment by joeykrug** [comment]
Yeah I like this idea

**Comment by bthaile** [comment]
https://app.clubhouse.io/augur/story/14414


I like this idea also. It was a feature initially but has gotten lost through the many revisions.

**Comment by adrake33** [comment]
Issue moved to [AugurProject/augur #338](https://github.com/AugurProject/augur/issues/338) via [**ZenHub**](https://www.zenhub.com/)
