### ISSUE TITLE
2 Universe Genesis?

### ISSUE THREAD

**Issue by page1** [AugurProject/augur-app#228]
I'm seeing double.
<img width="341" alt="screen shot 2018-07-23 at 12 06 59 pm" src="https://user-images.githubusercontent.com/6609556/43094731-ffeffacc-8e70-11e8-8227-ee082f011138.png">

Sorry about the waterfall of issues over the past few hours. Thank you for everyone else's contributions to make this app better day by day.

**Comment by nuevoalex** [comment]
Someone actually made another genesis universe. This is something anyone can do, though it would only be useful if you migrate everyone's REP manually or convince them to (REP is frozen in the new universe until this is done).

We're discussing filtering these other genesis universes out potentially.

**Comment by page1** [comment]
I see. I thought the only way to make a new universe was to have a forking dispute. And if that was what was happening, I was sort of hoping to see the market that was creating the issue.

But since you say anyone can make a new universe, someone could spam the creation of duplicates and really make this part of the UI messy.

**Comment by nuevoalex** [comment]
Agreed. I believe we should just filter out other genesis universes since the UI already specifies a default genesis universe.

**Comment by sharkcrayon** [comment]
This has been fixed now. Closing.
