### ISSUE TITLE
Successful limit orders but don't show on Augur

### ISSUE THREAD

**Issue by shane1900** [AugurProject/augur-app#230]
Hi,

Over the last 5 days I've submitted 5 limit orders but only the first is available to be seen under Portfolio > Transactions.  So I have no way to track my orders or cancel them.  

What happens when the market is over and my limit order was not filled, automatically refunded?

My node is up to date and I'm using Augur 1.05.  Any ideas?

**Comment by page1** [comment]
Hi @shane1900 do you see corresponding transactions in etherscan.io for your address? Maybe something is crashing when you send the orders? And they are not making it to ethereum network. What OS are you on? On Mac you can get logs from ~/Library/Logs/augur/log.log that may help others help you.

**Comment by shane1900** [comment]
Hello,

Yes I do see all transactions being confirmed on etherscan.io.  Attached are my Mac logs.  I'm connected to Metamask in Chrome.  Using my 2nd Metamask account.

[log.log](https://github.com/AugurProject/augur-app/files/2220950/log.log)

**Comment by shane1900** [comment]
Hi,

Yes I confirmed I'm looking at the "All" option.  

I've rebooted and tried both using my local Parity node and connecting to Augur Mainnet.  And tried switching Metamask accounts back and forth.  No luck :(

**Comment by nuevoalex** [comment]
@shane1900  Can you link the actual transactions on etherscan here?

**Comment by shane1900** [comment]
Sure here's the last one I did which I do not see.

https://etherscan.io/tx/0x21e851ed6b5d1aedcadc8e82c598f48223666f8ab64d8432694a683c7a5ed6bc

**Comment by nuevoalex** [comment]
@shane1900 That tx is using the method to only fill orders and not make any new ones. Did you have the "Fill Orders Only" box checked when making this tx?

**Comment by shane1900** [comment]
Yes I did check that.  I thought that box meant > fill the entire order and not do a partial fill.  Guess I was wrong?

Any way I can cancel it?

**Comment by shane1900** [comment]
Would you mind helping me understand what's happening.  Sounds like I put out orders to be filled and locked up ETH to do it.  Can I cancel this?

**Comment by page1** [comment]
From what I see in your transaction the order has run its course and the eth was returned since it wasn't able to fill against an existing order.
<img width="754" alt="screen shot 2018-07-31 at 2 50 22 pm" src="https://user-images.githubusercontent.com/6609556/43486459-2ab6a1fa-94d1-11e8-8a15-ce3252eb0e05.png">

@nuevoalex Let me know if I'm miss interpreting.

**Comment by sharkcrayon** [comment]
@shane1900 If the "fill orders only" checkbox is checked, this means that the Augur contracts will only attempt to fill orders that are already on the orderbook. If your order cannot be totally completed by filling orders (i.e. someone filled the available orders before your tx went through or the orders were cancelled) then the excess ETH escrowed for your order is returned to you.

If you don't check the checkbox, your order will be matched with any orders on the books, and whatever is left over will be used to place a new order on the books.

Does that clarify things?

**Comment by shane1900** [comment]
Thanks @sharkcrayon
