### ISSUE TITLE
Way to see markets ending soon

### ISSUE THREAD

**Issue by Sm00g15** [AugurProject/augur-app#232]
Is there currently a way to see markets that will be ending soon?

**Comment by bthaile** [comment]
Currently not in augur-ui. It is in out filter/search roadmap, I believe. 

This site has a way to search for recently ending markets

https://predictions.global

**Comment by bthaile** [comment]
Currently not in augur-ui. It is in out filter/search roadmap, I believe. 

This site has a way to search for recently ending markets

https://predictions.global
