### ISSUE TITLE
Cannot connect to local geth node

### ISSUE THREAD

**Issue by john-light** [AugurProject/augur-app#233]
Select configuration: Local
Configuration name: Local
HTTP Endpoint: http://localhost:8545
Websocket Endpoint: ws://localhost:8546

Running geth v1.8.12

After clicking "connect" I get the following errors:

`Server Error: "Block range 0x1 to 0 exceeds currentBlock 0"`

`Server Error: "Controller mismatch. Configured: 0xb3337164e91b9f05c87c7662c7ac684e8e0ff3e7 Found: undefined"`

Before experiencing this issue I also ran into this same issue:

https://augur.stackexchange.com/questions/767/augur-client-cant-connect-to-ethereum-node-on-local-network

Tried the suggested command when running geth:

`geth --rpc --ws --rpcaddr "0.0.0.0" --wsaddr "0.0.0.0" --rpccorsdomain "*" --wsorigins "*"`

which fixed the first error mentioned in that Stack Exchange post but then I got the errors mentioned above.

**Edit:** I changed my endpoints to point to 10.0.0.3 on the same ports as shown in the Stack Exchange post linked above and now the app just hangs on "Connecting...." for a while before returning the error:

`Server Error: "Could not connect via augur.connect Error: Connection failed"`

**Edit 2:** It's possible this is a node syncing issue. I've been at 99.9988% synced for a few hours now so not sure where to go from here...

**Comment by xenoexclusive** [comment]
The "Controller mismatch" error usually occurs if your client has not finished syncing.

In regards to your connection issues, try the following. Start geth with `geth --rpc --ws --wsorigins "127.0.0.1"` and nothing more. Then run Augur (after deleting appdata) with DEFAULT 'Local' settings IE `http://localhost:8545` and `ws://localhost:8546`.

The `--rpcaddr` and `--wsaddr` commands are unnecessary, and using `"*"` as a value for origins/domains is unsafe as it exposes it to every address.

Everything should run fine. If you check your geth node and you are still having WS warnings, then peculiarly some systems the `--wsorigins` command require `'127.0.0.1'` as opposed to `"127.0.0.1"`, so try that.

**Comment by sharkcrayon** [comment]
@john-light Any luck with @xenoexclusive's suggestions?

**Comment by john-light** [comment]
@sharkcrayon my geth node is consistently ~100 blocks behind, for whatever reason it doesn't want to catch up to the chain tip. Might have to try Parity.

**Comment by bthaile** [comment]
Make sure your geth node is running on a machine with SSD hard drive, drive speed can be a bottleneck. closing

**Comment by john-light** [comment]
Closing this issue for now as I have switched to try a Parity node (which also is having its own [issue](https://github.com/AugurProject/augur-app/issues/291)).
