### ISSUE TITLE
Designated Reporting without Sign in?

### ISSUE THREAD

**Issue by page1** [AugurProject/augur-app#240]
On 1.0.6 - "Open Augur App", you end up on "Markets" tab. Click "Reporting" and there is a market in the designated reporting section.... I haven't signed in, how could it know what account I'm using? And I highly doubt someone would have listed me as the designated reporter.
<img width="1270" alt="screen shot 2018-07-25 at 11 21 19 am" src="https://user-images.githubusercontent.com/6609556/43216748-fc8f6358-8ffc-11e8-8fd3-663358701fac.png">

This market goes away after sign in.

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/14555/github-designated-reporting-w-o-sign-in

**Comment by page1** [comment]
@bthaile I'm seeing the same issue in 1.0.7
<img width="1280" alt="screen shot 2018-07-26 at 10 33 35 am" src="https://user-images.githubusercontent.com/6609556/43275567-662c9b6a-90bf-11e8-8d40-246caf61780b.png">

**Comment by phoebemirman** [comment]
1.0.7 didn't have ui updates, just a hot fix. this will be in the next release 1.0.8
