### ISSUE TITLE
Resolved Markets

### ISSUE THREAD

**Issue by negamax** [AugurProject/augur-app#247]
Either it's an Ux issue or UI bug or combination of both

1. Second week of markets are settled now. They can be seen from Reporting -> Resolved. There's no indication of claiming settlement either from this window or from the market itself
2. Portfolio -> Positions. Still shows settled markets in 'in Reporting'. 'Calculate Payout' button triggers a Metamask prompt. It is not clear what's that for
3. Resolved markets list in (2) is empty. Although that shouldn't be the case due to (1)

**Comment by nuevoalex** [comment]
@sharkcrayon @matt-bullock I agree this seems to be a problem. People in discord generally confused by this as well.

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/14556/github-resolved-markets

**Comment by phoebemirman** [comment]
a change for this has been merged and will be in the next release.

**Comment by sharkcrayon** [comment]
Specifically, this is addressed:

> Portfolio -> Positions. Still shows settled markets in 'in Reporting'.
> Resolved markets list in (2) is empty. Although that shouldn't be the case due to (1)

They are now listed properly under Resolved (in the next release).

These two issues still need to be addressed:

> 'Calculate Payout' button triggers a Metamask prompt. It is not clear what's that for

Adding to issue tracker: https://app.clubhouse.io/augur/story/14577/github-make-calculate-payout-clearer-on-portfolio-positions-page

> I am afraid that many people may (will) go to their respective markets after the settlement. Click on 'Close' in front of the position, resulting in loss of funds. There should be some indication on Market itself, if the person has a winning position

Adding to issue tracker: https://app.clubhouse.io/augur/story/14899/github-highlight-winning-outcome-on-trading-page-and-change-close-position-button-to-claim-payout

**Comment by bthaile** [comment]
Internally discussing other feature requests in internal system. closing this
