### ISSUE TITLE
Very low gas prices with Edge wallet

### ISSUE THREAD

**Issue by enolan** [AugurProject/augur-app#248]
I'm using the Edge wallet and all the transactions get created with very low gas prices, and takes tens of minutes to hours to confirm. In the range of 1 - 1.5 gwei. I'm guessing it just uses the gas price reported from the Ethereum node, which is IIUC the median over the last few blocks.

**Comment by bthaile** [comment]
I’m not familiar with edge, do they allow the user to add more gas?

**Comment by enolan** [comment]
There's no options. AFAICT the transaction is created and signed in the
browser. You don't get a prompt on your phone or anything.

**Comment by bthaile** [comment]
Not being to change gas is an issue with ledger and I believe trezor as well. It’s on our radar. 

Keeping this open.

**Comment by bthaile** [comment]
working feature to allow users to change gas price in app. closing
