### ISSUE TITLE
App 1.07 not loading into brave browser - works with chrome

### ISSUE THREAD

**Issue by bamos01** [AugurProject/augur-app#249]
It was working previously.  App is fully synced - when I try to open with Brave- I just see Augur logo expanding and contracting

**Comment by bthaile** [comment]
Currently we don’t officially support brave. We’ve not even tested. Good idea though. Closing

**Comment by rashley60** [comment]
pg specifically asked that this issue be opened. Brave worked fine in 1.0.5, and something, perhaps a helmet change, changed in 1.0.6 or 7. This is maybe not a difficult fix and Brave support is kinda nice to brag about.

**Comment by bthaile** [comment]
https://app.clubhouse.io/augur/story/14648

We have an idea what broke it. We’ll check it out.

**Comment by justinbarry** [comment]
@rashley60 Replace "127.0.0.1" with "localhost" in the url bar. See: https://github.com/brave/browser-laptop/issues/13390

**Comment by bthaile** [comment]
No feedback for a while, considered resolved.
