### ISSUE TITLE
Javascript Error Returned in the Mainprocess

### ISSUE THREAD

**Issue by Anastik** [AugurProject/augur-app#256]
I get the following error message whenever I press "connect" after booting up the UI: 

<img width="425" alt="screen shot 2018-07-27 at 12 57 57 pm" src="https://user-images.githubusercontent.com/33998307/43346210-c7cd2da2-919c-11e8-80a8-1f1b8d5fb63d.png">

Then after pressing "Open Augur App" I get the following error on my browser:

<img width="1143" alt="screen shot 2018-07-27 at 12 59 01 pm" src="https://user-images.githubusercontent.com/33998307/43346225-d9e88432-919c-11e8-99ec-426eeab72519.png">

**Comment by bthaile** [comment]
We’ve seen this issue. We added a fix for the javascript error, to come out in next release. 

I think this error covers up the actual error. Can you look in the log file?

Log locations are here:
https://github.com/AugurProject/augur-app/blob/master/README.md

**Comment by petervecchiarelli** [comment]
Closing for now
