### ISSUE TITLE
Unable to claim outstanding returns

### ISSUE THREAD

**Issue by 7--** [AugurProject/augur-app#262]
> Augur 1.0.7
> Ledger
> Chrome
> wss://megageth.com/ethereum-ws,, wss://ponytail.io/ws, https://mainnet.infura.io/
> market "American league will win all star game?"

I'm unable to claim outstanding returns. When I press the claim button I get this error. I've tried running on different networks. 

![image](https://user-images.githubusercontent.com/4725003/43369105-14b5337c-9336-11e8-8ec9-b78151efef24.png)

@rty in discord is having the same issue with this market. And  @nuevoalex was trying to help us. 
"Which team will win the 2018 Fifa world cup?"

Full log:
[127.0.0.1-1532886522981.log](https://github.com/AugurProject/augur-app/files/2239031/127.0.0.1-1532886522981.log)

**Comment by bthaile** [comment]
What are your endpoints in augur-app?

Looks like you are connected to local ethereum node but the ws is set to remote geth node. Is that correct?

**Comment by 7--** [comment]
I've tried most of the endpoints on here but gives the same error:
https://predictions.global/augur-public-ethereum-nodes
![image](https://user-images.githubusercontent.com/4725003/43369759-4f349686-9341-11e8-9d5e-230bde8348a9.png)


This is my address. Doesn't seem to make a transaction. 
https://ethplorer.io/address/0x391d6390e08058dab2f9ac0bb9860056fc847b03

**Comment by nuevoalex** [comment]
@7-- This appear to be an issue of not having enough ETH to pay the TX cost. The account provided here in the screenshots only has .001 ETH which will not be enough to cover the tx cost

**Comment by 7--** [comment]
I added some more ETH but having the same issue. 
![image](https://user-images.githubusercontent.com/4725003/43371615-b5e0b0be-9363-11e8-9e81-59402698d3f0.png)

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/14661/github-unable-to-claim-outstanding-returns

**Comment by jragosa** [comment]
I'm experiencing similar difficulties to claim:

To be more detailed, i have the error "eth_call returned no data (0x)" when I'm connected through :
https://megageth.com/
wss://megageth.com/ws 
https://gethstar.com/
wss://gethstar.com/ws
wss://ponytail.io/ws

Different behavior when I'm connected through "https://ponytail.io/", the transaction gets to my ledger, I can confirm it but nothing happens.

**Comment by sharkcrayon** [comment]
@nuevoalex got a DM with the public address, just for the record.

**Comment by bthaile** [comment]
If this issue comes up again we'll reopen. Closing for now.

**Comment by sharkcrayon** [comment]
I'm not sure that we've looked into this enough to close it yet.

@jragosa @7-- Are you still having this issue?

**Comment by jragosa** [comment]
I was able to claim a few days later, I told @nuevoalex on Discord. But no new market I was involved in  resolved since then, so I haven't had a new opportunity to claim.

**Comment by sharkcrayon** [comment]
@bthaile Can you coordinate w/ @7-- to get what information you need here?

**Comment by bthaile** [comment]
@7– what endpoint are you using? Also can you try on version 1.2 just to make sure your augur-app is at the current version. 

Also can you try using the ‘https://gethnode.com/http’ endpoint.

**Comment by 7--** [comment]
I tried that endpoint and version 1.2, but am getting the same result. 
![image](https://user-images.githubusercontent.com/4725003/43988268-b2fe2dea-9cff-11e8-8e51-5391042391f9.png)

**Comment by nuevoalex** [comment]
@7-- Do you happen to remember the rough gas price on the network during this failure?

The gas required by the claim function is roughly 1.2 million, which mean with an account balance of only 0.18 you would only be able to afford this tx when gas prices are below ~15.

I suspect this is just not having enough gas for the tx. The current ledger support for displaying erorrs and adjusting gas is not great but it's something we do plan to improve.

Could you try the tx again today and see if it works since the median gas price is ~2.5?

**Comment by 7--** [comment]
That was the issue. When I added more ETH it worked.
