### ISSUE TITLE
Market Liquidity on Review Page is Incorrect If It's Adjusted.

### ISSUE THREAD

**Issue by stanfordjesse1** [AugurProject/augur-app#263]
On the review page, when you’re making a market, the total market liquidity is incorrect if you hit the "previous" button and delete orders. It shows the total that has been added both of the times, but it doesn’t account for the fact that I actually deleted my orders between the times I visited the review page.

If I subsequently hit back, and delete all my orders, and proceed to the review screen once more, it will still show 9.8 ETH, despite all orders being deleted. 

So in the screenshot below, it’s showing that the total market liquidity is 9.8 ETH, which is because I first made the market with 5 ETH, then went back and made it with 4.8 ETH. But it’s showing 9.8 ETH.

Meanwhile, if I go back and add orders, without deleting any of the original orders, then it's correct.

Furthermore, if I go back and delete all my orders, but then add 1 ETH worth of orders, the total will adjust to 10.8 ETH.

<img width="698" alt="screen shot 2018-07-29 at 10 24 00 pm" src="https://user-images.githubusercontent.com/2432185/43374672-db6ab896-937e-11e8-900f-808a90197349.png">

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/14662/github-market-liquidity-on-review-page-is-incorrect-if-it-s-adjusted

**Comment by adrake33** [comment]
@JohnDanz https://app.clubhouse.io/augur/story/14662/github-market-liquidity-on-review-page-is-incorrect-if-it-s-adjusted is marked as completed. Can this issue be closed?

**Comment by adrake33** [comment]
Closing this issue, since it should now be fixed.
