### ISSUE TITLE
v 1.0.6: Augur app stops syncing - shows 99.9%  wrongly

### ISSUE THREAD

**Issue by negamax** [AugurProject/augur-app#269]
I can interact with existing data. But if I make a new action like listing an order, reporting etc. It does not reflect. Looking at the Augur App window it shows 99.9%. But on restart it was ~3000 blocks behind

**Comment by bthaile** [comment]
Recommend v1.0.7 and using a community endpoint. Here is the list. 

https://predictions.global/augur-public-ethereum-nodes

See if that helps. We are still working on data stability and will have another release coming out.

**Comment by sharkcrayon** [comment]
@negamax Did @bthaile's suggestions work?

**Comment by negamax** [comment]
@sharkcrayon I moved to v1.0.7, have seen similar sync issue. My guess is this may be due to connection interruption. If my wifi drops suddenly (weather, network etc). Then this happens.

**Comment by sharkcrayon** [comment]
@epheph @nuevoalex What's the status with the Augur App/Node auto-reconnect feature? Is that released yet? I'm guessing that might address this issue.

**Comment by nuevoalex** [comment]
@sharkcrayon Not released yet. Should be in the next version

**Comment by negamax** [comment]
This works well on 1.1.1 @sharkcrayon @nuevoalex
