### ISSUE TITLE
Feature request : Variable Market Creator Bond 

### ISSUE THREAD

**Issue by negamax** [AugurProject/augur-app#270]
This can provide multiple benefits in terms of reducing random markets but biggest benefit could be that other UIs (third party) can filter by or show only markets that have higher bond to signal quality.

**Comment by adrake33** [comment]
Added to issue tracker: https://app.clubhouse.io/augur/story/16265/github-variable-market-creator-bond

**Comment by adrake33** [comment]
Closing this issue. It has been discussed and is being added to version 2 of the Augur smart contracts.
