### ISSUE TITLE
Show both Yes and No outcomes for binary markets

### ISSUE THREAD

**Issue by MarkWieczorek** [AugurProject/augur-app#281]
Markets with **N** outcomes list all **N** outcomes under the "outcomes" section of the user interface. However, for binary markets, where **N=2**, only a single **Yes** outcome is provided. 

This design decision will create endless confusion with newcomers that will never be resolved by any amount of education. For simplicity, the user should be able to buy a **No** share, without having to "short yes for a price of 1 - price of yes in order to receive negative yes shares". Such a change will be simple to implement in the user interface.

**Comment by nuevoalex** [comment]
@MarkWieczorek I tend to agree. @sharkcrayon @tinybike

**Comment by sharkcrayon** [comment]
I agree as well. We'll think through it this week while we're looking at redesigning parts of the trading page.

**Comment by joeykrug** [comment]
For binary markets imo this should be a setting in the UI. Choose whether you want to just go long or short [and don't _name_ the outcome anything IMO]. Or choose to see both yes + no

**Comment by bthaile** [comment]
Internal tracking system, It looks like we all agree. closing
https://app.clubhouse.io/augur/story/16009/show-both-yes-and-no-shares
