### ISSUE TITLE
Initial Trades Ignored During Create Market Stage 

### ISSUE THREAD

**Issue by LuckyDucky19** [AugurProject/augur-app#286]
When you are creating your own market, during the page to create an order to add liquidity to your market, the orders are just ignored.. IE MetaMask never asks to sign these transactions.  You have to place the trades after the market is created.

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/15115/github-initial-trades-ignored-during-create-market-stage

**Comment by sharkcrayon** [comment]
@LuckyDucky19 Did you have to refresh the page or did Augur App crash after you signed the create market transaction and before you got a chance to sign the initial liquidity transactions?

**Comment by sharkcrayon** [comment]
We're not able to reproduce this. Some changes in the pipeline make it so the user can sign initial liquidity transactions after creating the market.
