### ISSUE TITLE
404 error when opening app

### ISSUE THREAD

**Issue by MidnightLightning** [AugurProject/augur-app#304]
On Windows 10, launching the desktop app works fine and I can sync to the Infura default node for the most part.

The client eventually gets to a "99.9%" sync point, and shows the "Open Augur App" button as enabled. But clicking on that button opens my web browser to a "http://127.0.0.1:8080" URL that shows all white except for a "404 page not found" notice.

![capture](https://user-images.githubusercontent.com/250250/43992079-7e4d9556-9d3e-11e8-8a54-6f66aa314980.PNG)

![capture2](https://user-images.githubusercontent.com/250250/43992080-823d88e2-9d3e-11e8-8b68-eb0080d3caf4.PNG)

How do I get the actual web interface to appear correctly?

**Comment by bthaile** [comment]
What version of the app are you running?

**Comment by MidnightLightning** [comment]
@bthaile v1.2.0

**Comment by bthaile** [comment]
Try toggling ‘enable ssl for ledger’ maaybe that setting has an issue.

**Comment by MidnightLightning** [comment]
Huh, that worked! Setting the "Enable SSL for Ledger" option, then clicking the "Open Augur App" button worked! Though Chrome complained of a certificate error, I could click past that and load the page.

Then, if I clicked the "Disable SSL for Ledger", then the site still worked, so seems that something got set oddly, and toggling that option cleared it.
