### ISSUE TITLE
Can't claim Stake and Fees via Trezor

### ISSUE THREAD

**Issue by jazy510** [AugurProject/augur-app#307]
Unable to claim all available stake and fees, from the Portfolio -> Reporting page.  When the claim button is clicked, and then SUBMIT on the “REVEIW WITHDRAWAL” screen, Chrome seems to spawn the Trezor window (same window/frame where you enter in the PIN) - but then that window immediately closes and the error message appears:
TREZOR INFORMATION
Error signing transaction: "Window closed"

**Comment by nuevoalex** [comment]
@jazy510 Are there any errors in your browser console? If so could you please post them here.

Does the account you're attempting to claim from have a reasonable ETH balance to pay the gas fee for the TX?

**Comment by jazy510** [comment]
![image](https://user-images.githubusercontent.com/662519/44098880-2f0621fc-9f96-11e8-93b4-5cdc488caff6.png)
The account has an ETH balance > 10 ETH.  The trezor sign/ui window closes so fast, it seems like it's being spawned with something invalid making it immediately close.

**Comment by jazy510** [comment]
Here's the contents of the 1st:

transaction failed: Already waiting for a response 
{constant: false, name: "redeem", inputs: Array(1), signature: Array(1), returns: "bool", …}
constant
:
false
estimateGas
:
false
from
:
"0x[CORRECT ETH ADDRESS HERE]"
inputs
:
["_sender"]
name
:
"redeem"
params
:
["0x[CORRECT ETH ADDRESS HERE]"]
returns
:
"bool"
send
:
true
signature
:
["address"]
to
:
"0xf1d09........1d936a2c"
uuid
:
"16e00e33-25e6-4422-a63e-39b6 undefined 0xcb1ce48..[long sig snip'd].....1c83cb

**Comment by jazy510** [comment]
and the 2nd err:

wrap-on-failed-callback.js:11 transaction failed: Window closed
 {constant: false, name: "redeem", inputs: Array(1), signature: Array(1), returns: "bool", …}
  constant: false
  estimateGas: false
  from: "0x[CORRECT ETH ADDRESS HERE]"
  inputs: ["_sender"]
  name: "redeem"
  params: ["0x[CORRECT ETH ADDRESS HERE]"]
  returns: "bool"
  send: true
  signature: ["address"]
  to: "0x26d1d.....04d391e"
  uuid: "91fea31e-aaf1-4f53-9555-ecef557637bd"
  __proto__: Object undefined 0xceb8a666b7111...long sig snipp'd.......72394b

**Comment by jazy510** [comment]
This is the 2 same errors when attempting to claim in Brave:

![image](https://user-images.githubusercontent.com/662519/44128661-fdce7a40-9ff8-11e8-9935-50c63dd5d8a2.png)

**Comment by jazy510** [comment]
This is still occurring in 1.3.0

![image](https://user-images.githubusercontent.com/662519/44303722-2d958780-a2fd-11e8-9314-93779e9e04cb.png)

**Comment by bthaile** [comment]
Creating issue, different than claiming priceeds fix in 1.3

https://app.clubhouse.io/augur/story/15592

**Comment by jazy510** [comment]
fwiw, this remains an issue with 1.4.0, in Brave browser.

**Comment by nuevoalex** [comment]
@jazy510 do you get the same console errors as well?

**Comment by bthaile** [comment]
@jazy510 Have you tried using a different endpoint to connect to mainnet? recommend 

https://gethnode.com/http 
wss://gethnode.com/ws

**Comment by jazy510** [comment]
There seems to just be 1 error in Brave when attempting to claim, similar as before. Brave attempts to spawn the trezor window but fails and give this error:
> main.cb0a1ad37660b2a2f04c.js:1 transaction failed: Window closed Object undefined 

![image](https://user-images.githubusercontent.com/662519/45312864-1bfd6500-b4e2-11e8-8f01-cb85e714b572.png)

**Comment by jazy510** [comment]
Doesn't seem to be any popup setting, as I'm able to login OK via Trezor in Brave (Account -> Trezor -> Connect Trezor) with the popup window.
When attempting to claim (or do any signing, it seems) or Bidding on an Outcome, the same error happens:

> TREZOR INFORMATION
Error signing transaction: "Window closed"

**Comment by nuevoalex** [comment]
@jazy510 Does this occur in Chrome as well?

**Comment by adrake33** [comment]
Closing this for now because Brave is not officially supported by Augur. 

@jazy510 If you are seeing this issue in Chrome/Firefox, please feel free to reopen this ticket.
