### ISSUE TITLE
Mainnet configuration doesn't connect after 1.3.2 update

### ISSUE THREAD

**Issue by Vints** [AugurProject/augur-app#321]
One thing to note: I deleted the augur folder from ~/Library/Application Support/ which seemed to help in the past when I couldn't connect to the Mainnet.

After doing the above, I also deleted the log file and then re-attempted to connect. Here are the logs:
<img width="645" alt="screen shot 2018-08-20 at 5 42 23 pm" src="https://user-images.githubusercontent.com/6623399/44373896-6e79d180-a4a0-11e8-8ed6-11bcaef678a0.png">

Here's a screenshot of what I see:
<img width="950" alt="screen shot 2018-08-20 at 5 41 12 pm" src="https://user-images.githubusercontent.com/6623399/44373854-425e5080-a4a0-11e8-845b-acc74a6acf9b.png">

It just hangs on "Connecting..." and the logs don't seem to have any errors.

**Comment by bthaile** [comment]
gethnode.com is a community provided ethereum node, it might of had hiccups. 

Try the ‘local light node’ network configuration.

**Comment by petervecchiarelli** [comment]
Adding to issue tracker: https://app.clubhouse.io/augur/story/15647/github-mainnet-configuration-doesn-t-connect-after-1-3-2-update

**Comment by Vints** [comment]
I was able to get the local light node configuration working, so this issue can be closed :)

Although... I did run into another issue with local light node, but @nuevoalex put up this PR to fix it: https://github.com/AugurProject/augur-app/pull/323
