### ISSUE TITLE
can't open augur app

### ISSUE THREAD

**Issue by andyvauliln** [AugurProject/augur-app#322]
After i pressed open "augur app button" I was redirected to localhost 
http://127.0.0.1:8080/#/categories?augur_node=ws%3A%2F%2F127.0.0.1%3A9001&ethereum_node_http=http%3A%2F%2F127.0.0.1%3A8545&ethereum_node_ws=ws%3A%2F%2F127.0.0.1%3A8546

and nothing happening after this

I tried in mainet and also in local light mode

version 1.3.2 os mac sierra 10.12.6

**Comment by petervecchiarelli** [comment]
Adding to issue tracker: https://app.clubhouse.io/augur/story/15648/github-can-t-open-augur-app

**Comment by bthaile** [comment]
When you say nothing happens, does blank web page come up?
If so,
Can you try toggling ‘enable ssl for ledger’ in augur-app setting menu options? 

Then try to click on ‘Open Augur App’ button again.

**Comment by andyvauliln** [comment]
I dealt with it, thx
