### ISSUE TITLE
"My REP staked" is 0 but I've disputed things

### ISSUE THREAD

**Issue by enolan** [AugurProject/augur-app#326]
On the reporting/dispute page, it says my REP staked is zero, but I staked rep to dispute two markets. Is this a display issue, or did the disputing fail somehow?

Transaction 1: https://etherscan.io/tx/0x7931e4de2696822d5b8f3e4d7f1ad65aee4ea7e8c7beb8df84d6e4743fa4738d

Transaction 2: https://etherscan.io/tx/0x3c9c987fb2bb448929a162b5826af6ff26b292df4adb10d1f223b0b748df2abc

**Comment by bthaile** [comment]
I agree we need to display the REP that can be on the next fee window. I added a task for us to see whats the best approach. 

https://app.clubhouse.io/augur/story/15693

**Comment by bthaile** [comment]
We made changes to handle showing REP balance when user stakes on dispute and fills bond. We'll be releasing that in 1.5.
