### ISSUE TITLE
Checksums?

### ISSUE THREAD

**Issue by blake-regalia** [AugurProject/augur-app#328]
Perhaps I am doing something wrong, but my checksums are not consistent with what is being reported in release notes:

| **Platform** | **Checksum** |
| --- | --- |
| Mac | 0da999d014547f1d7d9715939f42a4371c5bf13cb6f834c5205cc58a8307947f |

```shell
$ openssl sha1 mac-Augur-1.4.0.dmg
SHA1(mac-Augur-1.4.0.dmg)= 1d3bc0e92027028f97edaf5f086e470a4987ded3

$ openssl sha1 mac-Augur-1.4.0.zip
SHA1(mac-Augur-1.4.0.zip)= cfc6bcdb58729798dfb84b43a20d96e8191c793a
```

Also:
```shell
$ cat latest-mac.yml
version: 1.4.0
files:
  - url: mac-Augur-1.4.0.zip
    sha512: dzzztrfxBIL45l06VZqVqcvj5d/e5tO7X4aKDu3GDpFugZvLXLyXPw/11BGOt86CSAxGSzCKeTFT3l1w4hYHfg==
  - url: mac-Augur-1.4.0.dmg
    sha512: 5aX00/Alk/6UgnaO6WQ1vFGRTFFYgQ5ylbsVx8yYCA90+Cz8+TnnJIF5Lt55S7OfPCZ0Rcu9FfnOKMJ5k4s+/w==
    size: 153655780
path: mac-Augur-1.4.0.zip
sha512: dzzztrfxBIL45l06VZqVqcvj5d/e5tO7X4aKDu3GDpFugZvLXLyXPw/11BGOt86CSAxGSzCKeTFT3l1w4hYHfg==
releaseDate: '2018-08-22T20:52:08.213Z'
```

```shell
$ openssl sha512 mac-Augur-1.4.0.dmg
SHA512(mac-Augur-1.4.0.dmg)= e5a5f4d3f02593fe9482768ee96435bc51914c5158810e7295bb15c7cc98080f74f82cfcf939e72481792ede794bb39f3c267445cbbd15f9ce28c279938b3eff

$ openssl sha512 mac-Augur-1.4.0.zip 
SHA512(mac-Augur-1.4.0.zip)= 773cf3b6b7f10482f8e65d3a559a95a9cbe3e5dfdee6d3bb5f868a0eedc60e916e819bcb5cbc973f0ff5d4118eb7ce82480c464b308a793153de5d70e216077e
```

**Comment by justinbarry** [comment]
@blake-regalia Thank you for the report! I will look into this.

**Comment by justinbarry** [comment]
@blake-regalia I cobbled together a script that emulates the behavior of electron-builder. I'm only commenting on the hashes in latest.yml.

```js
// sha-cli.js
const filename = process.argv[2];
const crypto = require('crypto');
const fs = require('fs');
const hash = crypto.createHash('sha512');
const input = fs.createReadStream(filename);
input.on('readable', () => {
    const data = input.read();
    if (data)
        hash.update(data);
    else {
        console.log(`${hash.digest('base64')} ${filename}`);
    }
});
```

And the output:
```
$ node check-hash.js mac-Augur-1.4.0.zip
dzzztrfxBIL45l06VZqVqcvj5d/e5tO7X4aKDu3GDpFugZvLXLyXPw/11BGOt86CSAxGSzCKeTFT3l1w4hYHfg== mac-Augur-1.4.0.zip
```
The output appears to be consistent with the values in the yml file.

I'm unsure why the hash is different across the different tools. Below is my attempt to rule out encoding and it doesn't appear to have worked.

```
$ echo mac-Augur-1.4.0.zip |  openssl dgst -binary -sha512 | openssl base64 -A
CwhXdxy9xlYiGKHjYQTjtOP+yKdQU4Fwx2KV9V0XXrd3o0codAbLTKVxRQvJn9P/BBdDRG6o52wQGEaTngiKYw==%
```

I have some questions out to other devs on the project wrt the hashes in the table.

**Comment by pgebheim** [comment]
The hashes in release-checksums.txt are SHA256.

They are calculated by CI before being uploaded to github.

These artifacts are then confirmed by a release tool by downloading the installer, computing the hash and then comparing the result with the SHA256 we uploaded to github.

If this all passes then we aggregate the checksums for all platforms into a file and sign it with the forecast Foundation public GPG key -- which is verifiable via pgp.mit.edu using the email address team@augur.net

Since 1.4.0 we've added the functionality to also directly generate the table that is added to the release notes after the artifacts have been published -- to further prevent human errors.

Ill verify all the checksums one more time.

@petong could you also verify?

**Comment by petong** [comment]
The checksums are generated using sha256, not sha1. We should probably clarify that somewhere:

```
❯ grep mac-Augur-1.4.0.dmg release-checksum.txt
0da999d014547f1d7d9715939f42a4371c5bf13cb6f834c5205cc58a8307947f mac-Augur-1.4.0.dmg

❯ openssl sha256 mac-Augur-1.4.0.dmg
SHA256(mac-Augur-1.4.0.dmg)= 0da999d014547f1d7d9715939f42a4371c5bf13cb6f834c5205cc58a8307947f

❯ gsha256sum mac-Augur-1.4.0.dmg
0da999d014547f1d7d9715939f42a4371c5bf13cb6f834c5205cc58a8307947f  mac-Augur-1.4.0.dmg


```
