### ISSUE TITLE
Transferred share tokens don't show up in position view

### ISSUE THREAD

**Issue by enolan** [AugurProject/augur-app#339]
I transferred some share tokens from one account to another, and they aren't showing up in the destination account and still show up in the sending account.

**Comment by bthaile** [comment]
Do you have a etherscan transaction? You can DM in discord.

**Comment by enolan** [comment]
https://etherscan.io/tx/0xd9370f8eb492cfecf91852f2bd57fc4e2a1a8e2593648ad9dc0cb50c78aa0ca2

**Comment by bthaile** [comment]
Internal issue tracking 
https://app.clubhouse.io/augur/story/15982/github-transferred-share-tokens-don-t-show-up-in-position-view

**Comment by bthaile** [comment]
@enolan Did you use myEtherWallet or myCrypto to try and move the shares?

**Comment by enolan** [comment]
I did it inside of MetaMask

**Comment by bthaile** [comment]
Is this the destination address `0xeeab37ed9f0fc208065af1be9a17c343e5e1b0bb`?

https://etherscan.io/token/0x3169a97a51b7b7f2d8cf87fe92b338ccdc6f33c0?a=0xeeab37ed9f0fc208065af1be9a17c343e5e1b0bb

looks like it has a balance of `10,000,000,000 SHARE`. Am I reading all that correct?

**Comment by bthaile** [comment]
“Our positions are populated entirely by trading actions. We don't support manual transfers in our UI at all yet and it will generally not perform well.” 

Here is our view on the subject of manually tranferring share tokens. 

We do have a task to help facilitate transferring share tokens. Its currently in discussion.

**Comment by nuevoalex** [comment]
To clarify the transfer appears to have been successful from the etherscan link that was posted, however this won't be displayed in the Augur client properly as it is based entirely on the results of trading.

**Comment by bthaile** [comment]
I see, @enolan would have to manually send a tx to claim winning proceeds. The UI relizes on augur-node for aggregated data. 

Currently augur-node doesnt recognize the manual transfer so the UI wont show properly. Portfolio positions view wonst show that there is a position therfore, The ‘claim proceeds’ button won’t show in the portfolio positions page.
