### ISSUE TITLE
Mac Download throwing 404 

### ISSUE THREAD

**Issue by beatelite** [AugurProject/augur-app#351]
On your release page: https://github.com/AugurProject/augur-app/releases

On the mac link: https://github.com/AugurProject/augur-app/releases/download/untagged-d8a41318d015415507b0/mac-Augur-1.4.0.dmg

I get 404.

**Comment by bthaile** [comment]
Thanks, we’ll make sure to fix that and verify the download link works for 1.5, coming out soon.

**Comment by petong** [comment]
links fixed
