### ISSUE TITLE
Antivirus app error

### ISSUE THREAD

**Issue by carl339** [AugurProject/augur-app#367]
Since 1.2 version, karpersky antivirus and it heuristic don't let me download the app, because identify the app like a trojan: Trojan.Win32.alien.generic, i don't know what to do, and i don't like to desactivate the antivirus to install it!

![screenshot_1](https://user-images.githubusercontent.com/43270797/45550003-48b9c100-b7ef-11e8-936e-f6928931aabd.jpg)

**Comment by adrake33** [comment]
@carl339 You may need to add Augur to Kaspersky's list of Trusted Applications. Try looking at https://support.kaspersky.com/11444 to see if that helps.

**Comment by adrake33** [comment]
@carl339 Closing this issue for now. If this is still a problem, please let me know.
