### ISSUE TITLE
is there an issue with checksums of 1.5.1 release ?

### ISSUE THREAD

**Issue by artlog** [AugurProject/augur-app#375]
https://augur.stackexchange.com/questions/782/checksum-verification-for-linux-users-of-augur-app/843#843

shasum -a 256 linux-Augur-1.5.1.AppImage
aae4d6a9452c4a7a0d77251101f9774d1e7d03387ec694eb9b9bdf0d496a08c2  linux-Augur-1.5.1.AppImage

cat linux-Augur-1.5.1.AppImage.sha256 
aae4d6a9452c4a7a0d77251101f9774d1e7d03387ec694eb9b9bdf0d496a08c2 linux-Augur-1.5.1.AppImage

this one is correct but :

 cat release-checksum-v1.5.1.txt
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

82ec39e0c7dafc4d299dc0163d94035783c4c5e31fd9928819a4aa3e4fc39550 linux-Augur-1.5.1.deb
9e8df5b3b97b2a69907f44f0a9c47f9dc19cfaafe345fb1cbc7c15d0b784671c mac-Augur-1.5.1.zip
8ff1fa6bf737a6b8c2f27a9f80821e163c4d25dda8d44548aeefca63a7c214df win-Augur-1.5.1.exe
d4cd7920e216e85dc1333265cfcd39a651667d7c579dce5c53a4f9ab7b7f676c mac-Augur-1.5.1.dmg
f9946acf53232fe73a3eabc1a51e71be293d4203321c264fdf1ebdd8896a9298 linux-Augur-1.5.1.AppImage
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQIcBAEBAgAGBQJboT+oAAoJEHh6vonCD2W6fewQAKzePrko+rP1PT6aYKOFvPAb
5eKWV0fmRm1DPJRNm2hmefGJQXPbCIj/r/Un+Fqni4QWazzK2PEuBVVPH+Uw8SDb
Cv7+4+4Kd/zRgr+L8c0nqgx5X0SBW0Xjurc3BvgpEA1+UMb0Huls6W3UPvKNdSIZ
VA2m3szRjBcu8Wc9J+NHTuH+4xZRfeJcRIydPjRgRq1eOsvvBaX1SaPhidS1D1SN
G4XYPC91frc4i6vUVMLOnIPqg6mzNw6xhlYdgHrE223hRs7QdJFbZaQ11OZVDHQ6
xqtsyEkCtBtko3Enyt5j9v/yWNBKIrWx1nbQEFwgph6dSdYPEDBZKM2CWOzjKus9
P5BpVomVnczJhcHQF7UUokV2l/CUaRsD9/Xgh6f8mq/NY/CD4F+jE7ZrdXGt9lJA
MNDiHLFV9i/WI/DhfKq7r6GATz6EFBO/qYDF0wpkicX2BbA8P8xHCKSNgFTenxL8
DlzZi4mR0EweGIGhF4Aeo07V4TELCHHsXJlE3hUsMOuFQmESlL+b29tOrh+v0DZv
ZvLpIle6PbSRTOnhtwdS0hAJPLfRqrxOU2toqs3IYPgVRuV3mxlmnAS1AVPyuAyL
wN/EmzbkmuMNIsW6PjHOXhvzgQq8xnW3hwcyMcMzEfVa6NlLEw0N8zspYd+UA1DQ
fxe+Di4FP1kncqzXAFIo
=zhhr

**Comment by adrake33** [comment]
Added to internal tracking system: https://app.clubhouse.io/augur/story/16825/github-update-checksum-for-augur-app-1-5-1

**Comment by petong** [comment]
Thanks for pointing this out, our CI system was triggered twice for this tag and some of the checksums did not match. the release-checksum fle should be accurate now.

**Comment by artlog** [comment]
thanks for your work.
