### ISSUE TITLE
error connect to mainnet

### ISSUE THREAD

**Issue by carl339** [AugurProject/augur-app#376]
i cant connect to the ethereum mainnet, im try reset database, erase config file and change Websocket endpoint: http://gethstar.com/ethereum-http, but nothing of this works!

![image](https://user-images.githubusercontent.com/43270797/45888808-98b2fd80-bd84-11e8-9471-a374ceade76f.png)

**Comment by bthaile** [comment]
MacOS : ~/Library/Logs/augur/log.log

Are there errors in your log file?


Windows : %USERPROFILE%\AppData\Roaming\augur\log.log

Linux : ~/.config/augur/log.log

**Comment by carl339** [comment]
I appear this:

![image](https://user-images.githubusercontent.com/43270797/45890697-36103080-bd89-11e8-997e-c76c8b7dd871.png)

I don't know, maybe a problem with the program database?

**Comment by carl339** [comment]
i resolve the problem, only delete the old database and works!! tks bthaile for give me the idea!!!

![image](https://user-images.githubusercontent.com/43270797/45890950-e41bda80-bd89-11e8-8001-614c6ac7e649.png)

**Comment by bthaile** [comment]
Awesome! Closing. 

Reopen this if your issue happens again.
