### ISSUE TITLE
 SQLITE_ERROR: table search_en has no column named consensusPayoutId

### ISSUE THREAD

**Issue by MrDThe** [AugurProject/augur-app#387]
Hi,

Update 1: I just removed folder C:\Users\%USERNAME%\AppData\Roaming\augur. Now it seems to connect and starting to download logs. 

I uninstalled all Augur software and re-installed the latest version (currently v1.6.2). 

When I start the software and Connect to the Mainnet, I get the following error message:

insert into `search_en` (`category`, `consensusPayoutId`, `creationBlockNumber`, `creationFee`, `designatedReportStake`, `designatedReporter`, `disputeRounds`, `endTime`, `feeWindow`, `finalizationBlockNumber`, `forking`, `initialReportSize`, `isInvalid`, `lastTradeBlockNumber`, `longDescription`, `marketCreator`, `marketCreatorFeeRate`, `marketCreatorFeesBalance`, `marketCreatorMailbox`, `marketCreatorMailboxOwner`, `marketId`, `marketStateId`, `marketType`, `maxPrice`, `minPrice`, `needsDisavowal`, `needsMigration`, `numOutcomes`, `numTicks`, `reportingFeeRate`, `resolutionSource`, `scalarDenomination`, `sharesOutstanding`, `shortDescription`, `tag1`, `tag2`, `universe`, `volume`) values ('SPORT', NULL, 5937093, '0.01', '0.349680582682291667', '0xaf71d0d1ec6304b83171f7d280b87276055dc77b', 0, 1531346400, '0x26d1d266a99d42c15b2c8adc87d293cdb04d391e', 6030359, 0, '349680582682291667', NULL, NULL, NULL, '0xaf71d0d1ec6304b83171f7d280b87276055dc77b', '0.01', '10000000000000000', '0xebf729dd684665371d78b9ab61b01f7eb204629c', '0xaf71d0d1ec6304b83171f7d280b87276055dc77b', '0x5d192f598ff29318013b3f269ae37590aa75b5f9', 1069, 'yesNo', '1', '0', 0, 0, 2, '10000', '0.0001', NULL, NULL, '25.962882775', 'Will England win against Croatia in the 2018 Fifa world cup?', 'WORLDCUP', 'FOOTBALL', '0xe991247b78f937d7b69cfc00f1a487a293557677', '28.089882775') - **SQLITE_ERROR: table search_en has no column named consensusPayoutId**

Resetting the database doesn't fix it.

**Comment by MrDThe** [comment]
Update 2: Removing the augur folder in roaming resolved the issue. I came from an older version of Augur (not being the previous version). Looks like the database upgrade went wrong or something like that.

**Comment by adrake33** [comment]
Closing this issue, as this will be fixed when version 1.7.0 is released.
