### ISSUE TITLE
v.1.8.0 A JavaScript error occured in the main process

### ISSUE THREAD

**Issue by tobutridaz** [AugurProject/augur-app#408]
Windows 10 / just updated to v.1.8.0 and am getting "A JavaScript error occured in the main process" on launch/connect. Augur worked without an issue for me in the prior release. 

Attaching screenshot
![image](https://user-images.githubusercontent.com/12191364/48831610-74b96b80-ed77-11e8-8429-7803bac6f4d7.png)

**Comment by adrake33** [comment]
@tobutridaz We are currently working on a minor release that should fix this issue.

**Comment by tobutridaz** [comment]
@adrake33 thx, will wait it out then

**Comment by adrake33** [comment]
Closing, since this was addressed in v1.8.1
