### ISSUE TITLE
Block returned null response

### ISSUE THREAD

**Issue by tobutridaz** [AugurProject/augur-app#410]
Can't connect to Parity node with the below block returning null. Killing the chain and re-syncing did not help. 

> Block 6039710 returned null response. This is usually an issue with a partially sync'd parity warp node. See: https://github.com/paritytech/parity-ethereum/issues/7411

**Comment by adrake33** [comment]
@tobutridaz This is a known issue with Parity when using warp-sync. Missing blocks and logs should eventually become available, but it will take some time. More info can be found here: https://github.com/AugurProject/augur-app#parity-and-warp-sync.
