### ISSUE TITLE
Improve top-level error handling in ethrpc

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur-app#417]
chwy was seeing the following error while running the Augur App on Rinkeby:

![12-10](https://user-images.githubusercontent.com/11491365/49751153-8ea4ea80-fc61-11e8-9863-2d1b90b16873.jpg)

We should make this and other top-level errors into warnings. We also need a less fragmented strategy for error handling/logging that works well across desktop & mobile.

**Comment by JohnDanz** [comment]
these errors are coming from ethrpc, specifically this file: https://github.com/ethereumjs/ethrpc/blob/master/src/block-management/start-polling-for-blocks.js 

Do we want to make these warnings? It seems like error is more appropriate.

**Comment by bthaile** [comment]
@pgebheim closing.
