### ISSUE TITLE
[BUG]Rounded or truncated position/quantity makes selling all shares difficult

### ISSUE THREAD

**Issue by ndorf** [AugurProject/augur-app#424]
### Summary
On the `/#/market?id=` page, the Net Position and Quantity for each outcome is displayed either rounded or truncated to 0.0001. The precise amount doesn't seem to be visible anywhere, so it's not possible to create a sell order for all of your shares.

 ### Steps to reproduce
Tell us how to reproduce the issue.
1. Acquire 1.012345 shares of any outcome
2. View the associated market; Net Position and Quantity will both be 1.0123
3. Sell the displayed quantity of shares (1.0123) -- now, the Quantity will be correctly displayed as 0.000045. But, it's too late, as sending a second order for this tiny amount would not be worth the gas. It's just dust now.
4. Note: in this example, as well as what I actually experienced, it's not clear if the amount was rounded or truncated. If it turns out to be rounded, then one could actually end up with an unexpected short position in the outcome, although this would at least be discernible from the order entry (>0 ETH cost).

 ### Expected behavior
The precise quantity of shares held should be displayed IMO.

 ### Screenshots
If applicable, add screenshots to help explain the problem.

 ### Environment
- Operating system: Debian
- Browser: Firefox

 ##### If using Augur App:
 - Augur App version: 1.8.3
- Are you connecting with a pre-existing option from the dropdown list of networks? Yes
    - If so, which one? Local light node (experimental)

**Comment by adrake33** [comment]
Thanks for filing this, @ndorf! We are considering how best to handle this in the UI and will follow up shortly.

**Comment by adrake33** [comment]
Talked to @Chwy5 about this, and he and @matt-bullock will discuss adding hovers to a select number of the fields on the trading page.

**Comment by bthaile** [comment]
On the new trading page, quantity and total cost goes to 9 decimal places. Let me know if that needs to a increase.
