### ISSUE TITLE
Misc JS warnings

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur-app#430]
@Chwy5 is seeing this when creating a yes/no market

![](https://cdn.discordapp.com/attachments/378059579524775938/524733174022930453/12-18.jpg)

**Comment by Chwy5** [comment]
![1-8prop.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/92b2145f-a276-4eae-a8b9-9b3e0b4b8388)

Already created a market and provided liquidity in pre provision...was searching transactions of filled trades on this market.   Could possibly be caused bc the transaction pg displays the information wrong on the filled orders

**Comment by bthaile** [comment]
this can be close.
