### ISSUE TITLE
Augur App Should wait for controller shutdown

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur-app#450]
One of the band-aids is to wait using setTimeout, but the controller shutdown interface is async, so the Promise resolution can be used to trigger the shutdown messaging.

@adrake33 -- not sure of ryan's workload but I think he can do this pretty quick.

**Comment by adrake33** [comment]
@pgebheim Sounds good. I'll pull it into this sprint for Ryan.

**Comment by bthaile** [comment]
@pgebheim can this be closed.

**Comment by pgebheim** [comment]
Yeah, close it.
