### ISSUE TITLE
[BUG]Can not add market to Favorite from Dispute list page

### ISSUE THREAD

**Issue by gabbello** [AugurProject/augur-app#452]
### Summary
Can not add market to Favorite by clicking on the star icon from Dispute list page. It works fine from any other page/section: Reporting, Resolved, Markets 

JS console doesn't capture any event/return any error.

### Environment
- Operating system: Ubuntu 16.04
- Browser: Chrome Version 71.0.3578.98 (Official Build) (64-bit)

Click on star icon here doesn't work:
![image](https://user-images.githubusercontent.com/2505749/51416611-f6185900-1b82-11e9-820b-6071a5126ce9.png)

##### If using Augur App:
 - Augur App version: 1.9.2

**Comment by bthaile** [comment]
Probably broken by url change from SEO changes.
