### ISSUE TITLE
[Feature Request] Ability to close a percentage of a user's position

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur-app#467]
This was originally discussed in https://github.com/AugurProject/augur-app/issues/425. Breaking out chwy's request for closing a percentage of a position into a separate issue, since John has implemented filling out the order form. This will need design guidance before it can be implemented.

**Comment by Chwy5** [comment]
Low priority...just a cool feature to allows for faster 1 trading.....Can come back to it after design of Port and AS pgs are complete
