### ISSUE TITLE
Readme links to empty page for OS installers

### ISSUE THREAD

**Issue by HDCharles** [AugurProject/augur-app#64]
empty link: https://github.com/AugurProject/augur-app/releases

note: the augur main website 'download app' also links to this empty page

**Comment by bthaile** [comment]
We are in the process of releasing to mainnet, when the rep migration is done we will release augur-app.

**Comment by bthaile** [comment]
Release is now available, closing this.

**Comment by bthaile** [comment]
Release is now available, closing this.
