### ISSUE TITLE
Cannot build from source with nodejs 10

### ISSUE THREAD

**Issue by blacktemplar** [AugurProject/augur-app#72]
Just wanted to mention here that building from source doesn't work with nodejs 10.
The issue is with the following dependency chain: augur-app -> augur-ui -> ethereumjs-ledger -> node-hid 0.7.2 (old version which does not support nodejs 10).
See also https://github.com/ethereumjs/ethereumjs-ledger/issues/6.

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/13586/github-cannot-build-from-source-with-nodejs-10-low-pri

**Comment by adrake33** [comment]
Closing this, since we are using node 10 and ledgerjs.
