### ISSUE TITLE
Database locked when switching configurations

### ISSUE THREAD

**Issue by negamax** [AugurProject/augur-app#73]
Switch config without completion of previous one. Click on Connect. Following error shows up (see bottom of screenshot)
<img width="896" alt="screen shot 2018-07-10 at 10 21 20" src="https://user-images.githubusercontent.com/1029486/42498003-5f89600e-842b-11e8-98d6-f87423524022.png">

**Comment by format37** [comment]
had the same issue. helped: close app, open again, wait for synced: 100%, press @Open augur app"

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/13587/database-locked-when-switching-configurations

**Comment by nuevoalex** [comment]
@negamax Can you still produce this issue on the latest version of augur-app? I haven't been able to reproduce it

**Comment by negamax** [comment]
@nuevoalex Just going through notifications now. Although sync issue in spirit of this report is resolved, I have noticed some crashes on 1.06 and error prompts. I will open another issue with screenshots.
