### ISSUE TITLE
Support for multiple accounts on a Ledger

### ISSUE THREAD

**Issue by alfiehub** [AugurProject/augur-app#75]
When connecting with a Ledger Nano S it would be nice to choose which account/address to use.

Currently a lot of users will not be able to use the app because of this, unless they transfer ETH/REP to the default chosen address.

**Comment by bthaile** [comment]
Currently we only support the default account. Yes, you will have to transfer your tokens to the default address. We'll be working out a solution.

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/13750/support-for-multiple-ledger-accounts

**Comment by bthaile** [comment]
Currently working this feature. Tracking internally. closing
