### ISSUE TITLE
Augur App on Mac crashes randomly

### ISSUE THREAD

**Issue by negamax** [AugurProject/augur-app#82]
It happens quite often. Could be some sync issue

**Comment by page1** [comment]
Just experienced this. Is there a place with logs we should submit to help debug?

**Comment by aakilfernandes** [comment]
Can confirm. By "app" I mean the electron app. There's no error or notification, it just silently crashes while browsing localhost.

**Comment by hoffmabc** [comment]
You can look in the log for more info:  ~/Library/Logs/augur/log.log

**Comment by aakilfernandes** [comment]
@hoffmabc thanks!

Opened up this issue for those who have an "Order Not Found" error

https://github.com/AugurProject/augur-app/issues/89

**Comment by page1** [comment]
Looking at ~/Library/Logs/augur/log.log as per @hoffmabc I see an error similar, but slightly different from #89

**Comment by TacoByte** [comment]
#77?

**Comment by elie222** [comment]
Can confirm this is still happening on 1.0.2. Silently crashes.

**Comment by petervecchiarelli** [comment]
Duplicate of #78. Please track progress there.
