### ISSUE TITLE
Suggestion: better "sync" messaging

### ISSUE THREAD

**Issue by aakilfernandes** [AugurProject/augur-app#84]
When you first start up, there's a "Synced: 0%" at the top right. I assumed this meant my chain wasn't synced, but since I'm using Infura I was confused assuming it should be auto-synced.

After a few minutes it jumped to 68%, so I assume this is syncing app-specific data (instead of the entire Ethereum chain).

So two suggestions:
1) Add some kind of animating loading icon to communicate the syncing is in progress
2) Communicate this is Augur specific data, and not a problem with an un-synced Ethereum node

**Comment by drwasho** [comment]
Definitely... this isn't a SPV wallet

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/13757/github-suggestion-better-sync-messaging

**Comment by sharkcrayon** [comment]
@aakilfernandes @ButtaTRiBot @drwasho 

Does this help? We obviously have more refining to do of the Augur App design, but I'm trying to find something that will work for now while not creating any new issues.

![image](https://user-images.githubusercontent.com/4355755/42708339-ec9457e6-86d4-11e8-887a-84a6c084a046.png)

**Comment by bthaile** [comment]
I just noticed. Bare in mind the 100% is an illistration, when augur-node is 2 blocks behind it might be at 99% but still green.

**Comment by sharkcrayon** [comment]
This design has been pushed with 1.0.4. I'd still love to hear any further feedback! Closing for now.

**Comment by aakilfernandes** [comment]
@sharkcrayon is it syncing chain data, or data from somewhere else? I assume somewhere else (cause otherwise it would start at 100% with Infura). So I'd use something like "syncing Augur data" instead of "syncing with mainnet node". But thats just IMHO and feel free to ignore =)

**Comment by sharkcrayon** [comment]
@aakilfernandes Augur Node is syncing with the Ethereum blockchain. It's reading log data and compiling/processing data for presentation in the UI.
