### ISSUE TITLE
Suggestion: Enable inspector

### ISSUE THREAD

**Issue by aakilfernandes** [AugurProject/augur-app#85]
It would help users report bugs

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/13759/github-suggestion-enable-inspector

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/13597/enable-inspector-for-users-to-submit-bugs

**Comment by sharkcrayon** [comment]
@aakilfernandes This is enabled now in version 1.0.4. You'll find it in the app's Settings menu.
