### ISSUE TITLE
Request: Fiat prices

### ISSUE THREAD

**Issue by aakilfernandes** [AugurProject/augur-app#86]
Would be great if we can get some kind of fiat estimation of costs when placing buy orders

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/13763/github-request-fiat-prices

**Comment by adrake33** [comment]
Issue moved to [AugurProject/augur #344](https://github.com/AugurProject/augur/issues/344) via [**ZenHub**](https://www.zenhub.com/)
