### ISSUE TITLE
App window too large on MacBook Pro 13 inch

### ISSUE THREAD

**Issue by page1** [AugurProject/augur-app#92]
The app window is too tall and I can't figure out how to resize it so it doesn't sit under the dock.

<img width="1116" alt="screen shot 2018-07-10 at 12 42 14 pm" src="https://user-images.githubusercontent.com/6609556/42530623-e5c7d7d2-843e-11e8-996a-a522248efdca.png">

**Comment by petervecchiarelli** [comment]
@page1 Is this prohibitive, could you give more context?

**Comment by page1** [comment]
Hi @petervecchiarelli 
I wouldn't call it prohibitive. So far it seems most of the buttons are above the dock most of the time. It's just inconvenient when things like the following happen. (Vanishing cancel button)
<img width="322" alt="screen shot 2018-07-10 at 4 53 35 pm" src="https://user-images.githubusercontent.com/6609556/42542022-225511ce-8462-11e8-8872-be4902da2cad.png">
And it looks weird vs my other apps that don't expand below the dock.

Users that have their dock configured to hide may not notice the issue at all.

**Comment by justinbarry** [comment]
@page1 We set the size here: https://github.com/AugurProject/augur-app/blob/master/src/main/main.js#L22

On my machine it appears much larger. I'll see what I can do to make it smaller.
<img width="900" alt="screen shot 2018-07-10 at 4 12 07 pm" src="https://user-images.githubusercontent.com/328965/42544305-b8aa9f9c-8465-11e8-8726-d81cebefc7c3.png">

**Comment by page1** [comment]
Just got 1.0.2 installed and even with auto hiding Dock I see this at the bottom
<img width="982" alt="screen shot 2018-07-11 at 9 58 18 am" src="https://user-images.githubusercontent.com/6609556/42584722-1c6ce7b6-84f1-11e8-83bd-d76882354dd0.png">

Yes that reset button is cut in half falling off the screen. And would be 100% covered by the dock if not hidden.

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/13764/github-app-window-too-large

**Comment by sharkcrayon** [comment]
We've got a fix in the work for this (https://app.clubhouse.io/augur/story/13690/augur-app-design-adjustments). We'll post an update when it's pushed!

**Comment by page1** [comment]
Yay it resizes, thank you all!

**Comment by bthaile** [comment]
We'll have a new slimmer design coming out in 1.0.4. there are menu options to save real estate in the UI.
Keep an eye out for the new release
